# Generated by Django 5.0.4 on 2024-04-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lfl',
            name='average_quantity_of_goods_in_a_receipt',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='lfl',
            name='conversion',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='lfldaily',
            name='average_quantity_of_goods_in_a_receipt',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='lfldaily',
            name='conversion',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
