# Generated by Django 5.0.4 on 2024-04-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfl', '0002_alter_lfl_average_quantity_of_goods_in_a_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lfldaily',
            name='target_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
