# Generated by Django 5.0.4 on 2024-04-26 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remote_id', models.UUIDField(help_text='billz id', unique=True)),
                ('company_id', models.UUIDField()),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='billz/brands/')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'db_table': 'billz_brand',
            },
        ),
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remote_id', models.UUIDField(help_text='billz id', unique=True)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Product measurement unit',
                'verbose_name_plural': 'Product measurement units',
                'db_table': 'billz_measurement_unit',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remote_id', models.UUIDField(help_text='billz id', unique=True)),
                ('company_id', models.UUIDField()),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
                'db_table': 'billz_shop',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remote_id', models.UUIDField(help_text='billz id', unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_open', models.BooleanField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='billz.productcategory')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product categories',
                'db_table': 'billz_product_category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remote_id', models.UUIDField(help_text='billz id', unique=True)),
                ('name', models.CharField(max_length=255)),
                ('main_image', models.ImageField(upload_to='billz/products/')),
                ('type_id', models.UUIDField()),
                ('barcode', models.CharField(max_length=50)),
                ('sku', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_variative', models.BooleanField()),
                ('rmt_updated_at', models.DateTimeField(null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='billz.brand')),
                ('measurement_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='billz.measurementunit')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='billz.product')),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='billz.productcategory')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'billz_product',
            },
        ),
        migrations.CreateModel(
            name='ProductShopPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remote_id', models.UUIDField(help_text='billz id', unique=True)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('retail_currency', models.CharField(blank=True, max_length=20, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_prices', to='billz.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='billz.shop')),
            ],
            options={
                'verbose_name': 'Product Shop price',
                'verbose_name_plural': 'Product Shop prices',
                'db_table': 'billz_product_shop_price',
            },
        ),
    ]
