# Generated by Django 5.0.4 on 2024-04-26 15:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billz', '0002_productattribute_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productshopprice',
            name='remote_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
