# Generated by Django 5.0.4 on 2024-04-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billz', '0003_alter_productshopprice_remote_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='company_id',
            field=models.UUIDField(null=True),
        ),
    ]
